version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
       DB_HOST: mysql
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/DB/init.sql:/docker-entrypoint-initdb.d/01-init.sql


  server:
    build: ./server
    container_name: my-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build: ./client
    command: npm run dev -- --host
    container_name: my-client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mysql_data:
